FROM golang:1.22-alpine AS build
RUN apk add gcc git linux-headers musl-dev
WORKDIR /packet-test-schedule

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./ ./
RUN go build -v ./cmd/client/pair1
RUN go build -v ./cmd/client/train1
RUN go build -v ./cmd/client/ndt7

ENTRYPOINT [ "./batch.sh" ]
